/**
 * This file generated by Apso.
 */
import { Test, TestingModule } from '@nestjs/testing';
import { test, testCreate } from './dtos/test.dto';
import { testController } from './test.controller';
import { testService } from './test.service';
import { CrudRequest } from '@nestjsx/crud';

const baseRequest: CrudRequest = {
  parsed: {
    fields: [],
    paramsFilter: [],
    search: {},
    filter: [],
    or: [],
    join: [],
    sort: [],
    authPersist: undefined,
    limit: 10,
    offset: 0,
    page: 1,
    cache: undefined,
  },
  options: {},
};

describe('testController', () => {
  let controller: testController;
  let spyService: testService;

  beforeEach(async () => {
    const ApiServiceProvider = {
      provide: testService,
      useFactory: () => ({
        createOne: jest.fn(() => []),
        getOne: jest.fn(() => {}),
      }),
    };
    const module: TestingModule = await Test.createTestingModule({
      controllers: [testController],
      providers: [testService, ApiServiceProvider],
    }).compile();

    controller = module.get<testController>(testController);
    spyService = module.get<testService>(testService);
  });

  it('should be defined', () => {
    expect(controller).toBeDefined();
  });

  it('should call testController get method', () => {
    const req: CrudRequest = { ...baseRequest };
    expect(controller.get(req)).not.toEqual(null);
    expect(spyService.getOne).toHaveBeenCalled();
  });

  it('should call testController create method', () => {
    const req: CrudRequest = { ...baseRequest };

    const dto = new test();
    controller.create(req, dto);
    expect(controller.create(req, dto)).not.toEqual(null);
    expect(spyService.createOne).toHaveBeenCalled();
  });

  // Add your tests here
});
