/**
 * This file generated by Apso.
 */
import { Module } from '@nestjs/common';
import { test } from './test.entity';
import { TypeOrmModule } from '@nestjs/typeorm';
import { testService } from './test.service';
import { testController } from './test.controller';

@Module({
  imports: [TypeOrmModule.forFeature([test])],
  providers: [testService],
  exports: [testService],
  controllers: [testController],
})
export class testModule {}
